const projectsData = [
  {
    id: "burgerhouse",
    title: "BurgerHouse - Cardápio Web com WhatsApp",
    category: "ecommerce",
    categoryName: "Delivery & WhatsApp",
    shortDesc: "Cardápio dinâmico com carrinho de compras, adicionais e envio de pedido direto no WhatsApp sem taxa de entrega.",
    fullDesc: "Aplicação de alta conversão para hamburguerias e restaurantes. Permite ao cliente escolher opcionais, montar combos, calcular entrega e enviar a comanda completa formatada direto no WhatsApp da loja sem pagar comissão a aplicativos de delivery.",
    techs: ["HTML5", "CSS3", "JavaScript", "LocalStorage", "WhatsApp API"],
    metrics: "Zero comissões de delivery | +28% na conversão de visitantes",
    demo: "https://lucasgabrielom.github.io/burgerhouse/",
    github: "https://github.com/LucasGabrielOM/burgerhouse",
    badge: "Sem Taxas de App",
    icon: "shopping-bag"
  },
  {
    id: "smack-chicken",
    title: "Smack Chicken - Ecossistema Operacional",
    category: "systems",
    categoryName: "Sistemas & Apps",
    shortDesc: "Sistema completo para restaurante: Cardápio Web, Caixa (PDV), Painel de Cozinha em tempo real e Vendas.",
    fullDesc: "Solução completa para gestão e operação de food service. Integra pedidos efetuados no site com a tela de comanda da cozinha em tempo real, controle de caixa (PDV) e relatórios financeiros.",
    techs: ["React", "Node.js", "Tailwind CSS", "WebSockets", "Vercel"],
    metrics: "+40% de velocidade nos pedidos | Zerou erros de comanda",
    demo: "https://smack-chicken.vercel.app/",
    github: "https://github.com/LucasGabrielOM/smack-chicken-painel-oficial",
    badge: "Solução Completa",
    icon: "utensils"
  },
  {
    id: "tah-imoveis",
    title: "TAH Imóveis - Portal Imobiliário",
    category: "websites",
    categoryName: "Websites & Landing Pages",
    shortDesc: "Portal imobiliário de alta velocidade com catálogo de imóveis, filtros por tipo/bairro e contato via WhatsApp.",
    fullDesc: "Website corporativo de alta performance para imobiliárias e corretores. Conta com navegação intuitiva, otimização SEO para buscadores e direcionamento de interessados direto para os corretores de plantão.",
    techs: ["HTML5", "CSS3", "JavaScript", "SEO", "Responsive UI"],
    metrics: "Catálogo online 24h | Captação direta de compradores",
    demo: "https://lucasgabrielom.github.io/tah-imoveis/",
    github: "https://github.com/LucasGabrielOM/tah-imoveis",
    badge: "Alta Conversão",
    icon: "home"
  },
  {
    id: "cortecerto",
    title: "CorteCerto - Açougue Fort",
    category: "systems",
    categoryName: "Sistemas & Apps",
    shortDesc: "Sistema de gestão para controle de quebra de carnes, cálculo de margem mensal e escala de folgas Kanban.",
    fullDesc: "Plataforma desenvolvida para gestão operacional de açougues e frigoríficos. Registra a desossa de peças, calcula o rendimento mensal de cada tipo de corte e organiza tarefas e folgas da equipe em quadro Kanban.",
    techs: ["JavaScript", "Chart.js", "Tailwind CSS", "REST API"],
    metrics: "-35% no desperdício de insumos | Gestão visual de equipe",
    demo: "https://lucasgabrielom.github.io/cortecerto-acougue-fort/",
    github: "https://github.com/LucasGabrielOM/cortecerto-acougue-fort",
    badge: "Gestão Operacional",
    icon: "layout-dashboard"
  },
  {
    id: "gatoffee-catcafe",
    title: "Gatoffee Cat Café",
    category: "websites",
    categoryName: "Websites & Landing Pages",
    shortDesc: "Website elegante e interativo para cafeteria temática com agendamento prévio e apresentação de cardápio.",
    fullDesc: "Landing page temática desenvolvida para fortalecer o branding da marca, apresentando o ambiente, cardápio de cafés e doces e sistema de reserva de mesas.",
    techs: ["HTML5", "CSS3", "JavaScript", "AOS Animations"],
    metrics: "Fortalecimento da marca | Agendamentos online",
    demo: "https://lucasgabrielom.github.io/gatoffee-catcafe/",
    github: "https://github.com/LucasGabrielOM/gatoffee-catcafe",
    badge: "Branding",
    icon: "coffee"
  },
  {
    id: "danzauu-tattoo",
    title: "Danzauu Tattoo Studio",
    category: "websites",
    categoryName: "Websites & Landing Pages",
    shortDesc: "Website portfólio para estúdio de tatuagem com galeria de artes e solicitação de orçamento pelo WhatsApp.",
    fullDesc: "Site com estilo Dark Modern projetado para destacar artes corporais, apresentar a trajetória dos artistas e facilitar a solicitação de orçamentos diretamente pelo WhatsApp.",
    techs: ["HTML5", "CSS3", "JavaScript", "Responsive UI"],
    metrics: "Galeria interativa | Captação de agendamentos",
    demo: "https://lucasgabrielom.github.io/danzauu-tattoo-web/",
    github: "https://github.com/LucasGabrielOM/danzauu-tattoo-web",
    badge: "Visual Premium",
    icon: "sparkles"
  },
  {
    id: "b2b-prospector",
    title: "B2B Technographics Prospector",
    category: "automation",
    categoryName: "Automações & IA",
    shortDesc: "Ferramenta B2B para prospecção automatizada, filtragem de empresas por CNAE e extração de contatos.",
    fullDesc: "Plataforma de inteligência comercial para vendas B2B. Minera dados públicos de empresas, mapeia negócios sem presença digital e qualifica leads comerciais.",
    techs: ["Python", "Node.js", "Web Scraping", "Data Cleansing"],
    metrics: "Prospecção qualificada de empresas locais",
    demo: "https://b2b-technographics-prospector.onrender.com/login?next=/dashboard",
    github: "https://github.com/LucasGabrielOM/b2b-technographics-prospector",
    badge: "Prospecção Ativa",
    icon: "target"
  },
  {
    id: "pncp-automation",
    title: "Sistema de Automação PNCP (Licitações)",
    category: "automation",
    categoryName: "Automações & IA",
    shortDesc: "Sistema em Python para coleta, filtro e análise automática de contratos públicos e licitações do governo.",
    fullDesc: "Robô de raspagem de dados que monitora diariamente os editais publicados no Portal Nacional de Contratações Públicas (PNCP), filtrando oportunidades por palavra-chave e gerando relatórios.",
    techs: ["Python", "Pandas", "REST APIs", "Data Scraping"],
    metrics: "Economia de 15h/semana em pesquisas manuais",
    demo: "https://lucasgabrielom.github.io/agencia-tech-site/",
    github: "https://github.com/LucasGabrielOM/sistema-automacao-pncp-python",
    badge: "Inteligência de Dados",
    icon: "bot"
  }
];
