const projectsData = [
  {
    id: "smack-chicken",
    title: "Smack Chicken - Ecossistema Operacional",
    category: "systems",
    categoryName: "Sistemas & Apps",
    shortDesc: "Sistema completo para restaurante: Cardápio Web, Caixa (PDV), Painel de Cozinha em tempo real e Dashboard Operacional.",
    fullDesc: "Desenvolvimento de uma solução end-to-end para operação de food service. O sistema integra pedidos feitos pelos clientes com a impressão/tela da cozinha, controle de caixa (PDV) e relatórios operacionais em tempo real.",
    techs: ["React", "Node.js", "Tailwind CSS", "WebSockets", "Supabase"],
    metrics: "+40% de velocidade nos pedidos | ZEROU erros de comanda na cozinha",
    github: "https://github.com/LucasGabrielOM/smack-chicken",
    badge: "Solução Completa",
    icon: "utensils"
  },
  {
    id: "burgerhouse",
    title: "BurgerHouse - Cardápio Web com WhatsApp",
    category: "ecommerce",
    categoryName: "Delivery & WhatsApp",
    shortDesc: "Landing page e sistema de pedidos dinâmico com carrinho de compras e envio imediato formatado para o WhatsApp.",
    fullDesc: "Aplicação focada em conversão para hamburguerias e restaurantes. Permite ao cliente escolher adicionais, montar combo, calcular taxa e enviar a comanda pronta direto no WhatsApp da loja sem pagar taxas de apps de delivery.",
    techs: ["HTML5", "CSS3", "JavaScript", "LocalStorage", "WhatsApp API"],
    metrics: "Zero comissões de delivery | Conversão estimada em 28%",
    github: "https://github.com/LucasGabrielOM/burgerhouse",
    badge: "Sem Taxas de App",
    icon: "shopping-bag"
  },
  {
    id: "cortecerto",
    title: "CorteCerto - Açougue Fort",
    category: "systems",
    categoryName: "Sistemas & Apps",
    shortDesc: "Sistema corporativo para controle de quebra de carnes, cálculo de margem e escala de trabalho Kanban.",
    fullDesc: "Plataforma desenvolvida para gestão de açougues e frigoríficos. Registra a desossa de peças, calcula rendimento mensal de cada tipo de carne e gerencia escalas de folga e tarefas da equipe via quadro Kanban.",
    techs: ["JavaScript", "Chart.js", "Tailwind CSS", "REST API"],
    metrics: "-35% no desperdício de peças | Gestão visual de equipe",
    github: "https://github.com/LucasGabrielOM/cortecerto-acougue-fort",
    badge: "Gestão Operacional",
    icon: "layout-dashboard"
  },
  {
    id: "tah-imoveis",
    title: "TAH Imóveis - Portal Imobiliário",
    category: "websites",
    categoryName: "Websites & Landing Pages",
    shortDesc: "Website institucional imobiliário com busca de imóveis, filtros avançados e contato via WhatsApp.",
    fullDesc: "Portal web de alta velocidade para catálogo de imóveis residenciais e comerciais. Conta com navegação intuitiva, otimização SEO para buscadores da região e integração de leads diretamente para os corretores.",
    techs: ["HTML5", "CSS3", "JavaScript", "SEO", "Responsive UI"],
    metrics: "Presença digital 24/7 | Captação direta de compradores",
    github: "https://github.com/LucasGabrielOM/tah-imoveis",
    demo: "https://lucasgabrielom.github.io/tah-imoveis/",
    badge: "Alta Conversão",
    icon: "home"
  },
  {
    id: "pncp-automation",
    title: "Sistema de Automação PNCP (Licitações)",
    category: "automation",
    categoryName: "Automações & IA",
    shortDesc: "Sistema em Python para coleta, filtro e análise automática de contratos públicos e oportunidades no PNCP.",
    fullDesc: "Script de raspagem e inteligência de mercado que monitora publicaçoes oficiais do governo federal e prefeituras, identifica oportunidades por palavra-chave e gera relatórios consolidados em planilhas.",
    techs: ["Python", "Pandas", "REST APIs", "Data Scraping"],
    metrics: "Economia de 15 horas/semana de pesquisa manual",
    github: "https://github.com/LucasGabrielOM/sistema-automacao-pncp-python",
    badge: "Inteligência de Dados",
    icon: "bot"
  },
  {
    id: "b2b-prospector",
    title: "B2B Technographics Prospector",
    category: "automation",
    categoryName: "Automações & IA",
    shortDesc: "Ferramenta B2B para prospecção automatizada, filtragem de empresas por CNAE e extração de contatos.",
    fullDesc: "Sistema projetado para apoiar vendas B2B. Minera dados corporativos, identifica empresas sem presença digital ativa e qualifica leads prontos para abordagem comercial.",
    techs: ["Python", "Node.js", "Web Scraping", "Data Cleansing"],
    metrics: "Base qualificada para disparo comercial",
    github: "https://github.com/LucasGabrielOM/b2b-technographics-prospector",
    badge: "Prospecção Ativa",
    icon: "target"
  },
  {
    id: "gatoffee-catcafe",
    title: "Gatoffee Cat Café",
    category: "websites",
    categoryName: "Websites & Landing Pages",
    shortDesc: "Website elegante e interativo para cafeteria temática com agendamento prévio.",
    fullDesc: "Landing page temática com design acolhedor, apresentação de cardápio exclusivo e sistema de reserva de mesas.",
    techs: ["HTML5", "CSS3", "JavaScript"],
    metrics: "Fortalecimento de marca e agendamentos",
    github: "https://github.com/LucasGabrielOM/gatoffee-catcafe",
    badge: "Branding",
    icon: "coffee"
  },
  {
    id: "danzauu-tattoo",
    title: "Danzauu Tattoo Studio",
    category: "websites",
    categoryName: "Websites & Landing Pages",
    shortDesc: "Website portfólio para estúdio de tatuagem com galeria de artes e orçamento via WhatsApp.",
    fullDesc: "Site com visual Dark Modern, focado em destacar trabalhos de arte corporal e simplificar a solicitação de orçamentos diretamente pelo WhatsApp do estúdio.",
    techs: ["HTML5", "CSS3", "JavaScript"],
    metrics: "Captação de agendamentos diretos",
    github: "https://github.com/LucasGabrielOM/danzauu-tattoo-web",
    badge: "Visual Premium",
    icon: "sparkles"
  }
];
